### PR TITLE
Update Codes.php

### PR DESCRIPTION
**Pull request by nimasdj**
This array is too much more complete around 10 countries more than previous one. for sure you can compare your first array with this one https://gist.github.com/vxnick/380904#gistcomment-1433576 Also it should return the original code if not found.

### CODE REVIEW

**Comment by nimasdj** [comment]
@julien-c When will you merge it and release  a version? This repo is still maintained?

**Comment by julien-c** [comment]
Please fix indentation, thanks

**Comment by nimasdj** [comment]
@julien-c I'll do that on Monday but I am thinking to add a separate array and method for getPhoneCode() too. It returns phone code by iso code. Do you like me to add this too?
Then you should add a separate method for menu selector for phoneCode yourself, like the one you did for iso codes. Ok?

**Comment by nimasdj** [comment]
@julien-c I did fix indentation, please merge it and release a new version as we need to install it via Composer asap.

**Comment by julien-c** [comment]
Merged. Do you want me to add you as contributor? That way you can tag the release yourself.

**Comment by nimasdj** [comment]
@julien-c if you don't have time to release a new version, then yes, you might want to add me as contributor that I would release a new version. But please note that in future, I would not take any action here without letting you know before, even if you make me as a cotributor.

**Comment by nimasdj** [comment]
@julien-c Sorry, I see new release is not affected on packagist, I renamed 1.2.0 to v1.2.0 and not yet affected please check why it is not affected on packagist?

**Comment by julien-c** [comment]
So, first of all, I've just set up the Github repo and Packagist account so that the Packagist distribution is auto-updated from now on.

**Comment by nimasdj** [comment]
I disvcovered the issue. It was because you had version in composer.json, I removed it from composer.json and re-released the version, now it is on packagist. You should not add version in composer.json.

**Comment by julien-c** [comment]
Yep. `1.2.0` is on Packagist now. Cheers

**Comment by nimasdj** [comment]
I also edited old versions and removed leading "v" from tags. You should not have leading "v" nor a version in composer.json, now I fixed everything.

**Comment by julien-c** [comment]
Ok, but in theory you shouldn't rewrite existing tags (like `1.1.0`) as it might change stuff for existing users of the library.

**Comment by nimasdj** [comment]
Ok, you have reason, but nothing dangerous will happen to them, may be just will be re-updated for them without any coding break. But I keep it in mind in future. :-)

**Pull request merged**
